// website/src/routes/index.tsx
import { gosub_svg, under_construction } from "../assets.ts";

export default function Home() {
  return (
    <main>
      <h1>
        <img src={gosub_svg} alt="GOSUB" width="236" height="64" />
      </h1>
      <h2>Serve Go modules from a GitHub repo subdirectory</h2>
      <img
        src={under_construction}
        alt="Under construction"
        width="64"
        height="64"
      />
      <p>Under construction!</p>
      <p>
        {"Here’s the "}
        <a href="https://github.com/more-please/gosub-goproxy">GitHub repo</a>
        {" if you just want the code."}
      </p>
    </main>
  );
}

// gosub/website/src/routes/+page.svelte
<svelte:head>
  <title>GOSUB</title>
  <meta
    name="description"
    content="Serve Go modules from a GitHub repo subdirectory"
  />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
</svelte:head>

<div class="content">
  <h1>
    <img src="$lib/gosub.svg" alt="utf-64" width="236" height="64" />
  </h1>
  <h2>Serve Go modules from a GitHub repo subdirectory</h2>

  <h3>
    <img
      src="$lib/under-construction.svg"
      alt="Under construction"
      width="128"
      height="128"
    />
  </h3>
  <h3>Under construction</h3>

  <h3>
    <a href="https://github.com/more-please/gosub-goproxy">
      <img src="$lib/github-mark.svg" alt="GitHub" width="20" height="20" />
      more-please/gosub-gproxy
    </a>
  </h3>
</div>

<style>
  .content {
    font-family: sans-serif;
    display: flex;
    flex-flow: column nowrap;
    align-items: center;
    margin: 0 0 4em;
  }
  img {
    vertical-align: middle;
  }
  a {
    text-decoration: none;
  }
  h1,
  h2 {
    margin: 0;
    padding: 1em 0 0.25em;
    max-width: 16em;
  }
  h1 {
    font-size: 3em;
    font-weight: bolder;
    text-align: center;
  }
  h2 {
    font-size: 1.5em;
    font-weight: normal;
    text-align: center;
  }
</style>
