// website/src/routes/index.tsx
import { ParentComponent, Show, children } from "solid-js";
import { Result, isErr, isOK } from "gosub-goproxy/result.ts";

import { GoproxyConfig } from "gosub-goproxy/goproxy.ts";
import { createStore } from "solid-js/store";
import { gosubEncode } from "gosub-goproxy/gosub.ts";
import { gosub_svg } from "../assets.ts";

const Row: ParentComponent = (props) => <div class="row">{props.children}</div>;
const Col: ParentComponent = (props) => <div class="col">{props.children}</div>;

const Input: ParentComponent<{
  id: string;
  placeholder: string;
  value: string | undefined;
  setValue: (value: string) => void;
}> = (props) => (
  <Col>
    <label for={props.id}>{props.children}</label>
    <input
      id={props.id}
      name={props.id}
      type="text"
      size="80"
      placeholder={props.placeholder}
      value={props.value ?? ""}
      onInput={(e) => props.setValue(e.currentTarget.value)}
    />
  </Col>
);

function getAsset(path: string): string {
  return new URL(`../../../${path}`, import.meta.url).href;
}

export default function Home() {
  const [config, setConfig] = createStore<GoproxyConfig>({
    url: "",
    tagPrefix: "v",
  });
  const encoded = () => gosubEncode(config);
  return (
    <main>
      <h1>
        <img src={getAsset("gosub.svg")} alt="GOSUB" width="236" height="64" />
      </h1>
      <h2>Serve Go modules from a GitHub repo subdirectory</h2>

      <Input
        id="url"
        placeholder="https://github.com/<user>/<repo>"
        value={config.url}
        setValue={(url) => setConfig("url", url)}
      >
        GitHub URL for your Go module:
      </Input>

      <Show
        when={isErr(encoded())}
        keyed
        fallback={<p>Looks good! Now let's locate your module…</p>}
      >
        {(result) => (
          <p>
            <em>{result.err}</em>
          </p>
        )}
      </Show>

      <Input
        id="directory"
        placeholder="optional/sub/directory"
        value={config.directory}
        setValue={(dir) => setConfig("directory", dir)}
      >
        Subdirectory:
      </Input>
      <Input
        id="prefix"
        placeholder="prefix-"
        value={config.tagPrefix}
        setValue={(p) => setConfig("tagPrefix", p)}
      >
        Version tag prefix:
      </Input>
      <Input
        id="suffix"
        placeholder="-suffix"
        value={config.tagSuffix}
        setValue={(s) => setConfig("tagSuffix", s)}
      >
        Version tag suffix:
      </Input>

      <Show when={isOK(encoded())} keyed>
        {(result) => (
          <>
            <h2>Result</h2>
            <p>{result.value}</p>
          </>
        )}
      </Show>
    </main>
  );
}

// website/src/routes/+page.svelte
<script lang="ts">
  import type { PageData } from "./$types";

  export let data: PageData;
  let { url, dir, prefix, suffix, result, hostError } = data;
</script>

<svelte:head>
  <title>Gosub</title>
  <meta
    name="description"
    content="Serve Go modules from a Github repo subdirectory"
  />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
</svelte:head>

<div class="content">
  <h1><img src="$lib/gosub.svg" alt="GOSUB" width="236" height="64" /></h1>
  <form method="get">
    <label>
      GitHub URL: <input name="url" type="text" bind:value={url} />
    </label>
    <label>
      Subdirectory: <input name="dir" type="text" bind:value={dir} />
    </label>
    <label>
      Tag prefix: <input name="prefix" type="text" bind:value={prefix} />
    </label>
    <label>
      Tag suffix: <input name="suffix" type="text" bind:value={suffix} />
    </label>
    <button>Submit</button>
  </form>
  <p>{hostError}</p>
  <p>{result}</p>
</div>
